### ISSUE TITLE
❓ Variables unused in calctimes.py

### ISSUE THREAD

**Issue by MasterCruelty** [ANTLab-polimi/CHIMA#1]
I found a couple of variables initialized to <code>0</code> and <code>None</code> but unused.
I link the source file: [measurements/calctimes.py](https://github.com/ANTLab-polimi/CHIMA/blob/master/measurements/calctimes.py)

Lines 6 and 7
```ruby
6 prev = 0
7 pre_desc = None
```

**Comment by simotone97** [comment]
thank you for the flag!

**Comment by MasterCruelty** [comment]
> thank you for the flag!

Glad to help

**Comment by simotone97** [comment]
fixed
